on:
    push:
      branches:
      - master
jobs:
  build:

    env:
      TWINE_USERNAME:  ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      PKG_TYPE: PROD
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:      run: |
      python -m pip install --upgrade pip
      pip install -r requirements_build.txt
      python --version
      python setup.py sdist bdist_wheel
      python -m twine upload dist/*